// Shared mutable state for replay recording, playback, and live trails.

export const ReplayRuntime = {
	recording: false,
	recordingStartedAt: null,
	recordedFrames: [],
	recordedRendering: null,
	recordedViewport: null,
	recordedPlayerStyle: null,
	recordedSources: null,
	recordedEnvironments: [],
	recordedWallTuples: null,
	lastRecordedEnvironmentStateRevision: null,
	currentRecordedEnvironmentRevision: -1,
	recordedRenderIds: new Map(),
	nextRecordedRenderId: 1,
	recordedEnemyDefinitions: [],
	recordedEnemyDefinitionIds: new Set(),
	recordedProjectileDefinitions: [],
	recordedProjectileDefinitionIds: new Set(),
	loadedReplay: null,
	playbackActive: false,
	playbackPlaying: false,
	playbackFrameIndex: 0,
	playbackStartedAt: 0,
	playbackBaseTimeMs: 0,
	playbackSpeed: 1,
	trailHistory: [],
	liveTrailSequence: 0,
	playbackHydratedReplay: null,
	playbackHydratedFrameIndex: -1,
	playbackHydratedSnapshot: null,
};
